# Site settings
title: JUG Ostfalen
email: jens@jug-ostfalen.de
description: > # this means to ignore newlines until "include:"
  JUG Ostfalen ist die Java User Group für Ostfalen, oder Braunschweig und Wolfsburg, für
  diejenigen die sich mit den historischen Regionsbezeichnungen nicht so auskennen.
include: ['_pages']
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jug-ostfalen.de" # the base hostname & protocol for your site
twitter_username: JUG_Ostfalen
github_username:  JUG-Ostfalen
image: http://www.jug-ostfalen.de/assets/main/jug_twitter.png

# organizations
orgs:
  JUG:
    description: Die JUG Ostfalen selbst
    image: logo.png
  entwicklerstammtisch:
    description: Der Wolfsburger Entwicklerstammtisch
    image: hacktalk.png
  hackcamp:
    description: Das Barcamp-ähnliche Hacking-Event in Wolfsburg
    image: hackcamp-gross.png
  sandsmedia:
    description: "S&S Media, Macher der JAX und sponsoren uns regelmässig mit Java Magazinen"
    image: sands_logo.png
  ijug:
    description: "Die iJUG ist ein Verbund der deutschsprachigen JUGs, in der auch die JUG Ostfalen Mitglied ist"
    image: ijug-logo.png
  jug-und-net:
    description: "Die JUG Ostfalen in Kooperation mit der .NET User Group Braunschweig"
    image: jug-net.png
  doag:
    description: "Deutscher Oracle Anwender Gruppe"
    image: doag.jpg

#Veranstaltungsorte
locations:
  lineas:
    name: "LINEAS"
    street: "Theodor-Heuss-Str. 2"
    city: "38122 Braunschweig"
    url: "http://www.lineas.de"
  ckc:
    name: "CKC Group"
    street: "Am Alten Bahnhof 13"
    city: "38122 Braunschweig"
    url: "http://www.ckc-group.de/"
  triology:
    name: "TRIOLOGY GmbH"
    street: "Brabandtstraße 9 – 10"
    city: "38100 Braunschweig"
    url: "http://www.triology.de/"
  onsite:
    name: "T-Systems on site services GmbH"
    street: "Alessandro-Volta-Straße 11"
    city: "38440 Wolfsburg"
    url: "https://www.t-systems-onsite.de/"
  schiller40:
    name: "Schiller40 Coworkingspace"
    street: "Schillerstr. 40"
    city: "38440 Wolfsburg"
    url: "http://www.wolfsburg.de/kultur/kulturwerk/schiller40-coworking-space"
  neosIT:
    name: "NeosIT GmbH"
    street: "Schachtweg 1"
    city: "38440 Wolfsburg"
    url: "https://neos-it.de/"
  mlc:
    name: "Mobile Life Campus (MLC)"
    street: "Hermann-Münch-Straße 1"
    city: "38440 Wolfsburg"
#Autoren
authors:
  uwe:
    display_name: "Uwe Sauerbrei"
    blurb: "Gründer der JUG-Ostfalen, jetzt in Hamburg unterwegs"
    url: https://www.xing.com/profile/Uwe_Sauerbrei
  jens:
    display_name: "Jens Schauder"
    blurb: "Organisator der JUG seit Herbst 2014"
    url: http://blog.schauderhaft.de/uber-jens-schauder/
  steven-schwenke:
    display_name: "Steven Schwenke"
    blurb: "Organisator des HackTalks Wolfsburg und des Entwicklerstammtisches"
    url: http://stevenschwenke.de/
  gerrit:
    display_name: "Gerrit Meier"
    blurb: "Irgendwie mit im Boot der JUG-Ostfalen"

# Build settings
markdown: kramdown
future: true
