# Site settings
title: JUG Ostfalen
email: jens@jug-ostfalen.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
include: ['_pages']
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jug-ostfalen.de" # the base hostname & protocol for your site
twitter_username: jensschauder
github_username:  JUG-Ostfalen

# organizations
orgs:
  JUG:
    description: Die JUG Ostfalen selbst
    image: logo.jpg
  entwicklerstammtisch:
    description: Der Wolfsburger Entwicklerstammtisch
    image: entwicklerstammtisch.jpg
  sandsmedia:
    description: "S&S Media, Macher der JAX und sponsoren uns regelmässig mit Java Magazinen"
    image: sands_logo.png

#Autoren
authors:
  uwe:
    display_name: "Uwe Sauerbrei"
    blurb: "Gründer der JUG-Ostfalen, jetzt in Hamburg unterwegs"
    url: https://www.xing.com/profile/Uwe_Sauerbrei
  jens:
    display_name: "Jens Schauder"
    blurb: "Organisator der JUG seit Herbst 2014"
    url: http://blog.schauderhaft.de/uber-jens-schauder/

# no code highlighting for now, since it does not work on windows. see for example http://stackoverflow.com/questions/17364028/jekyll-on-windows-pygments-not-working/17404260#17404260 
highlighter: false

# Build settings
markdown: kramdown